backend:
  name: github
  repo: Ruandersonvieira/ruandersonvieira.com

media_folder: content/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: '{{day}}-{{month}}-{{year}}--{{slug}}'
    fields:
      - { name: slug, label: slug, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: tags, label: Tags }
      - {
        label: Category,
        name: category,
        widget: relation,
        collection: categories,
        searchFields: ['title'],
        valueField: category,
      }
      - { name: banner, label: Banner, widget: image }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    slug: '{{day}}-{{month}}-{{year}}--{{slug}}'
    fields:
      - { name: slug, label: slug, widget: 'string' }
      - { name: title, label: Title }
      - { name: tags, label: Tags }
      - { name: techs, label: Techs }
      - { name: banner, label: Banner, widget: image }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }

  - name: categories
    label: Categories
    folder: content/categories/pt
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: categories,
        }
      - { label: Category name, name: title, widget: string }
      - { label: Description, name: description, widget: string }