backend:
  name: github
  repo: Ruandersonvieira/ruandersonvieira.com

media_folder: content/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: tags, label: Tags }
      - { name: image, label: Image, widget: image }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: tags, label: Tags }
      - { name: techs, label: Techs }
      - { name: image, label: Image, widget: image }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
